repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile, black]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
   - id: flake8
     additional_dependencies: [flake8-typing-imports==1.7.0]
     args: ['--ignore=E501,E203,E731,W503']
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
      args:
            - --keep-output
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    args: ['--ignore=D107,D204,D213,D203']
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==22.3.0]
   - id: nbqa-pyupgrade
     additional_dependencies: [pyupgrade==2.31.0]
   - id: nbqa-isort
     additional_dependencies: [isort==5.12.0]
     args: [--profile=black]
   - id: nbqa-flake8
     additional_dependencies: [flake8==4.0.1]
     args: ['--ignore=E501,E402,E203,E731,W503']
