[tool.poetry]
name = "madness-deblender"
version = "v1.0_beta1"
description = "Galaxy deblender from variational autoencoders"
authors = ["Biswajit Biswas <biswas@apc.in2p3.fr>"]
readme = "README.md"
keywords = ["galaxies", "deblending", "cosmology", "generative models"]
license = "MIT"
include = ["madness_deblender/data/*"]
repository = "https://github.com/b-biswas/madness"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"
pandas = "*"
astropy = "*"
tensorflow = {version = "^2.15.0" }
# macOS-specific dependencies
tensorflow-macos = { version = "2.15", markers = "sys_platform == 'darwin'" }
#tensorflow = { version = "2.15", markers = "sys_platform == 'darwin'" }
tensorflow-metal = { version = "*", markers = "sys_platform == 'darwin'" }

# Linux-specific dependencies
tensorflow-probability = "0.23"
scikit-image = "*"
sep = "*"
galcheat = "*"

matplotlib = {version="*", optional=true}
seaborn = {version="*", optional=true}
pytest = {version="*", optional=true}
pre-commit = {version="*", optional=true}
jupyter = {version="*", optional=true}
ipykernel = {version="*", optional=true}
autograd = {version="*", optional=true}
proxmin = {version="*", optional=true}
pybind11 = {version="*", optional=true}


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
notebooks = ["jupyter", "ipykernel", "btksims", "matplotlib", "seaborn"]
dev = ["pytest", "pre-commit", "jupyter", "ipykernel", "matplotlib", "seaborn"]
