survey_name: LSST

# Data paths for training models
TF_DATASET_PATH:
  HSC: /sps/lsst/users/bbiswas/simulations/HSC/
  LSST: /sps/lsst/users/bbiswas/simulations/LSST/

# Paths for comparing deblenders (used for testing purposes)
TEST_DATA_PATH:
  HSC: /sps/lsst/users/bbiswas/simulations/HSC/test_data/
  LSST: /sps/lsst/users/bbiswas/simulations/LSST/test_data/
RESULTS_PATH:
  HSC: /sps/lsst/users/bbiswas/MADNESS_results/HSC/
  LSST: /sps/lsst/users/bbiswas/MADNESS_results/LSST/

btksims:
  ORIGINAL_CAT_PATH:
    HSC: [
      "/sps/lsst/users/bbiswas/HSC_catalog/real_galaxy_catalog_26_extension_detrefined.fits",
      "/sps/lsst/users/bbiswas/HSC_catalog/real_galaxy_catalog_26_extension_detrefined_fits.fits",
    ]
    LSST: /sps/lsst/users/bbiswas/OneDegSq.fits
  CAT_PATH:
    HSC: [
      "/sps/lsst/users/bbiswas/HSC_catalog/real_galaxy_catalog_26_extension_detrefined.fits",
      "/sps/lsst/users/bbiswas/HSC_catalog/real_galaxy_catalog_26_extension_detrefined_fits.fits",
    ]
    LSST: /sps/lsst/users/bbiswas/OneDegSq_snr_10.fits

  # Training and validation parameters
  TRAIN_DATA_SAVE_PATH:
    HSC: /sps/lsst/users/bbiswas/simulations/HSC/
    LSST: /sps/lsst/users/bbiswas/simulations/LSST/
  TRAIN_VAL_PARAMS:
    btk_seed: 993
    stamp_size: 15
    maxshift: 2
    btk_batch_size: 100
    isolated_params:
      max_number: 1
      min_number: 1
      unique_galaxies: true
    blended_params:
      max_number: 3
      min_number: 1
      unique_galaxies: false
    training:
      LSST:
        index_range: [0, 150000]
        num_batches: 1500
      HSC:
        index_range: [0, 100000]
        num_batches: 1000
    validation:
      LSST:
        index_range: [150000, 200000]
        num_batches: 500
      HSC:
        index_range: [100000, 150000]
        num_batches: 250

  # Test parameters
  TEST_DATA_SAVE_PATH:
    HSC: /sps/lsst/users/bbiswas/simulations/HSC/test_data/
    LSST: /sps/lsst/users/bbiswas/simulations/LSST/test_data/
  TEST_PARAMS:
    btk_seed: 13
    stamp_size: 41
    maxshift: 15
    btk_batch_size: 20
    high_density:
      min_number: 12
      max_number: 20
    low_density:
      min_number: 8
      max_number: 15
    unique_galaxies: True
    LSST:
      index_start: 200000
      num_files: 300
    HSC:
      index_start: 150000
      num_files: 200
